#!/usr/bin/env bash

set -euo pipefail

format_branch() {
  local color=$1
  local label=$2
  local branch=$3
  local marker=" "

  [[ $branch == $CURRENT_BRANCH ]] && marker="*"

  printf "${color}[${label}]${COLOR_RESET} ${marker} ${branch}\n"
}

readonly COLOR_RECENT="\033[35m"
readonly COLOR_LOCAL="\033[34m"
readonly COLOR_REMOTE="\033[33m"
readonly COLOR_CURRENT="\033[1;32m"
readonly COLOR_RESET="\033[0m"

readonly CURRENT_BRANCH=$(git branch --show-current)

BRANCH_LIST=$(
  (
    # fetch recent checkout branches
    git reflog show --all | grep 'checkout: moving from' | awk '{print $NF}' | awk '!seen[$0]++' | while read branch; do
      format_branch "$COLOR_RECENT" "RECENT" "$branch"
    done
    # fetch local branches
    git branch --sort=-authordate --format="%(refname:short)" | awk '!seen[$0]++' | while read branch; do
      format_branch "$COLOR_LOCAL" "LOCAL" "$branch"
    done
    # fetch remote branches
    git branch --sort=authordate -r --format="%(refname:short)" | awk '!seen[$0]++' | while read branch; do
      format_branch "$COLOR_REMOTE" "REMOTE" "$branch"
    done
  ) | awk '!seen[$NF]++' # remove duplicates based on branch name
) 

SELECTED_BRANCH=$(
  echo "$BRANCH_LIST" \
  | fzf \
  --header-first \
  --header 'checkout branch' \
  --ansi \
  --layout=reverse \
  --preview-window=right,60% \
  --preview "
    branch=\$(echo {} | awk '{print \$NF}');
    git log --color=always --date=short -n 50 --oneline \
    --pretty=format:'%C(yellow)%h %C(cyan)%ad %C(reset)%s' \$branch 2>/dev/null \
    || echo \"not found \$branch branch, deleted\"
  " \
  | awk '{print $NF}'
)

if [[ $SELECTED_BRANCH =~ origin/ ]]; then
  LOCAL_BRANCH=${SELECTED_BRANCH#origin/}
  git checkout -b "$LOCAL_BRANCH" "$SELECTED_BRANCH" 2>/dev/null || git checkout "$LOCAL_BRANCH"
else
  git checkout "$SELECTED_BRANCH"
fi